# Generated by Django 4.1 on 2022-09-01 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name_plural': 'MOVIE'},
        ),
    ]
